### ISSUE TITLE
POM entry missing

### ISSUE THREAD

**Issue by vsrepalle** [SudhaSanthakumar/OAuth2#1]
<dependency>
			<groupId>com.us</groupId>
			<artifactId>models</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

Getting error as com.us.models jar is missing.

**Comment by vsrepalle** [comment]
Nice work and nice videos..Please help me with the above issue if i am missing. Thanks.

**Comment by ManuelSanchez1793** [comment]
i had the same isssue the dependency models is missing in POM of project :(

**Comment by SudhaSanthakumar** [comment]
you can find the missing pom project here....https://github.com/SudhaSanthakumar/OauthModels

**Comment by SudhaSanthakumar** [comment]
> com.us models 0.0.1-SNAPSHOT
> Getting error as com.us.models jar is missing.

you can find the missing pom project here....https://github.com/SudhaSanthakumar/OauthModels

**Comment by SudhaSanthakumar** [comment]
> com.us models 0.0.1-SNAPSHOT
> Getting error as com.us.models jar is missing.

Added the missing dependency project
